In [5]:
#generating numpy array with random data

import numpy as np
array_=np.random.randn(2,3)
print(array_)

[[ 0.43224081 -0.32826898 -0.08023839]
 [-0.00880015 -0.11261308  0.36630059]]


In [6]:
array_*10



array([[ 4.32240812, -3.2826898 , -0.80238392],
       [-0.08800148, -1.12613077,  3.66300589]])

In [7]:
array_+array_



array([[ 0.86448162, -0.65653796, -0.16047678],
       [-0.0176003 , -0.22522615,  0.73260118]])

In [8]:
array_.shape


(2, 3)

In [9]:
array_.dtype

dtype('float64')

In [10]:
data=[1,2,3]
np.array(data)

array([1, 2, 3])

In [17]:
data1=[[1,2],[3,4]]
data1=np.array(data1)
data1.ndim



2

In [18]:
data1.shape

(2, 2)

In [19]:
data1.dtype

dtype('int32')

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.empty((2,3,2))

array([[[4.45057637e-308, 1.78021527e-306],
        [8.45549797e-307, 1.37962049e-306],
        [1.11260619e-306, 1.78010255e-306]],

       [[1.42409073e-306, 4.45058910e-308],
        [8.45596650e-307, 9.34602321e-307],
        [4.94065646e-322, 8.32379756e-071]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
np.empty_like((2,3,2))

array([-218555792,        560,          0])

In [29]:
arr1=np.array([1,2,3], dtype=np.float64)

In [30]:
arr1.dtype

dtype('float64')

In [36]:
arr2=np.array([1.12,2.2,3.3])
arr2.astype(np.int32)


array([1, 2, 3])

In [37]:
arr2.astype(np.int64)

array([1, 2, 3], dtype=int64)

In [38]:
#Calling astype always creates a new array (a copy of the data), even
#if the new dtype is the same as the old dtype

In [46]:
np.empty(8,dtype='u4')

array([4016303024,        560,          0,    5570652,        616,
                0,        768,        560], dtype=uint32)

In [49]:
arr11=[1,2,3]
arr22=[2,3,4]
ar11=np.array(arr11)
ar22=np.array(arr22)
arr11 > arr22

False

In [54]:
arr_slic=ar11[1:]
arr_slic

array([2, 3])

In [59]:
arr_slic[:]=63
ar11

array([ 1, 63, 63])

In [61]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [62]:
data = np.random.randn(7, 4)
data

array([[-0.44702637, -0.85002032,  0.11370754, -0.06936034],
       [ 0.88707747, -0.44024513, -1.52656469,  0.11477497],
       [-0.96180714,  0.14032725,  0.62609691,  0.2514206 ],
       [-1.3503009 ,  1.56814109,  0.76363086,  0.6038585 ],
       [ 0.82754697,  0.69375371,  2.31314478,  0.83176893],
       [-0.1883192 , -0.59851157,  0.96118753,  1.00811832],
       [ 0.48091008,  0.71069186, -0.11798579, -0.22821256]])

In [63]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

In [64]:
data[names=="Bob"]

array([[-0.44702637, -0.85002032,  0.11370754, -0.06936034],
       [-1.3503009 ,  1.56814109,  0.76363086,  0.6038585 ]])

In [65]:
data[names=="Bob",2:]

array([[ 0.11370754, -0.06936034],
       [ 0.76363086,  0.6038585 ]])

In [66]:
#invert a condition
cond=names=="bob"
data[~cond]

array([[-0.44702637, -0.85002032,  0.11370754, -0.06936034],
       [ 0.88707747, -0.44024513, -1.52656469,  0.11477497],
       [-0.96180714,  0.14032725,  0.62609691,  0.2514206 ],
       [-1.3503009 ,  1.56814109,  0.76363086,  0.6038585 ],
       [ 0.82754697,  0.69375371,  2.31314478,  0.83176893],
       [-0.1883192 , -0.59851157,  0.96118753,  1.00811832],
       [ 0.48091008,  0.71069186, -0.11798579, -0.22821256]])

In [68]:
 data[names != 'Joe'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.88707747, -0.44024513, -1.52656469,  0.11477497],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.1883192 , -0.59851157,  0.96118753,  1.00811832],
       [ 0.48091008,  0.71069186, -0.11798579, -0.22821256]])

In [1]:
arr2d=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
#passing multiple indexes
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [3]:
#randn do generate some random normally distributed data:


In [4]:
arr = np.empty((8, 4))
arr

array([[1.69759663e-313, 8.94493575e-312, 8.94463840e-312,
        0.00000000e+000],
       [0.00000000e+000, 8.94493575e-312, 8.94463840e-312,
        0.00000000e+000],
       [0.00000000e+000, 8.94493456e-312, 8.94493578e-312,
        0.00000000e+000],
       [0.00000000e+000, 8.94493457e-312, 8.94493578e-312,
        0.00000000e+000],
       [0.00000000e+000, 8.94493576e-312, 8.94463840e-312,
        0.00000000e+000],
       [0.00000000e+000, 8.94500946e-312, 8.94500946e-312,
        8.94500946e-312],
       [8.94500946e-312, 8.94500946e-312, 8.94500946e-312,
        8.94500833e-312],
       [8.94500833e-312, 8.94500833e-312, 8.94500833e-312,
        8.94500833e-312]])

In [6]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [7]:
#To select out a subset of the rows in a particular order, you can simply pass a list or
#ndarray of integers specifying the desired order:

In [11]:
arr[[4,3,0]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.]])

In [13]:
arr[[-4,-3,-0]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [0., 0., 0., 0.]])

In [17]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [18]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [23]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [28]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [35]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [36]:
np.sqrt(arr)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131]],

       [[2.82842712, 3.        , 3.16227766, 3.31662479],
        [3.46410162, 3.60555128, 3.74165739, 3.87298335]]])

In [37]:
 np.exp(arr)

array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03]],

       [[2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
        [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]]])